version: "3"
services:
  ot-build:
    build: .
    ports:
      - "6969:6969"
    command: -d /tmp
    environment:
      - REDIRECT_URL=https://google.com
  ot-image:
    image: anthonyzou/opentracker
    ports:
      - "8888:8888"
    command: -d /tmp -p 8888
    environment:
      - REDIRECT_URL=https://google.com
